[default]
SUPABASE_URL = "https://pjhgxmxjsncqnzxeqdjt.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqaGd4bXhqc25jcW56eGVxZGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODgxMTUsImV4cCI6MjA2NDc2NDExNX0.H-UY1jbbutuUFUeSMrozPdEzqA4UTT_b7HWeF4Ljo3Q"
service_role="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqaGd4bXhqc25jcW56eGVxZGp0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTE4ODExNSwiZXhwIjoyMDY0NzY0MTE1fQ.SahPk8JpgwE6qv4eUbIRu97k1YIzmilK7oH_mL6KHwE"


